- name: Info Test
  hosts: localhost
  gather_facts: no
  become: no

  vars:
    do_debug: False

  pre_tasks:
    - debug: msg="DEBUG | pre_tasks"
    - info:
        state: setup
        prefix: info
        suffix: .json
        path: /tmp
      register: info_file
      delegate_to: localhost
    - debug: msg="DEBUG | {{ info_file }}"

  tasks:
    - debug: msg="DEBUG | tasks"
    - info:
        state: send
        step: "Step something:"
        msg: "We do something"
        file: "{{ info_file['path'] }}"
      delegate_to: localhost
    - tempfile:
       state: directory
       suffix: .alex
    - tempfile:
       state: directory
       suffix: .berta
   
  post_tasks:
    - debug: msg="DEBUG | post_task"
